Chatbot/urls.py
from django.urls import path
from . import views

app_name = "Chatbot"

urlpatterns = [
    path('accueil_chatbot', views.accueil_chatbot, name='accueil_chatbot'),
    path('chatbot_app', views.chatbot_application, name='chatbot_app'),
    path('documents_chatbot', views.documents_chatbot, name='documents_chatbot'),
    path('ajout_doc_temp', views.ajout_document_template, name='ajout_doc_temp'),
    path('ajout_doc_fct', views.ajout_document_fonction, name='ajout_doc_fct'),
    path('remove_doc/<str:document_name>', views.remove_doc, name='remove_doc'), 
    path('get_sources', views.get_sources, name='get_sources'),
    path('documents_chatbot2', views.documents_chatbot2, name='documents_chatbot2'),
    

]

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('', views.accueil_user, name='accueil'),
    path('contact/', views.contact, name='contact'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('signup/entreprise/', views.entreprise_signup, name='entreprise_signup'),
    path('add_salarie/', views.add_salarie, name='add_salarie'),
    path('salarie_list/', views.salarie_list, name='salarie_list'),
    path('delete_salarie/<int:salarie_id>/', views.delete_salarie, name='delete_salarie'),
]

gestion_ressources_V2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ress/', include('ressources.urls')),
    path('accounts/', include('accounts.urls')),
    path('simulateur_paie/', include('simulateur_paie.urls')),
    path('Chatbot/', include('Chatbot.urls')),
]

ressources/urls.py
from django.urls import path
from . import views

app_name = "ressources"

urlpatterns = [
    path('', views.index, name='index'),
    path('accueil', views.accueil, name='accueil'),
    path('ajouter-utilisateur/', views.create_user, name='create_user'),
    path('ajouter-objet/', views.create_objet, name='create_objet'),
    path('ajouter-resa/<int:obj_id>/', views.create_resa, name='create_resa'),
    path('edit-utilisateur/<int:utili_id>/', views.edit_user, name='edit_user'),
    path('edit-objet/<int:obj_id>/', views.edit_objet, name='edit_objet'),
    path('edit-resa/<int:resa_id>/', views.edit_resa, name='edit_resa'),
    path('edit-condi/<int:resa_id>/', views.edit_condi, name='edit_condi'),
    path('supp-utilisateur/<int:utili_id>/', views.remove_user, name='remove_user'),
    path('supp-objet/<int:obj_id>/', views.remove_objet, name='remove_objet'),
    path('supp-resa/<int:resa_id>/', views.remove_resa, name='remove_resa'),
    path('supp-condi/<int:condi_id>/', views.remove_condi, name='remove_condi'),
    path('events/', views.calendar_events, name='calendar_events'),
    path('calendar/', views.calendar_view, name='calendar_view'),
    path('choix-famille/<int:nbr_fam>/', views.choix_famille, name='choix_famille'),
    path('utili-liste', views.liste_utili, name='utili-liste'),
    path('objet-liste', views.liste_objet, name='objet-liste'),
    path('resa-liste', views.liste_resa, name='resa-liste'),
    path('ajout-resa', views.create_resa2, name='ajout-resa'),
    path('ajouter-condition/', views.create_condition, name='create_condition'),
    path('condi-liste/', views.liste_condition, name='condi-liste')
]

simulateur_paie/urls.py
from django.urls import path
from . import views

app_name = "simulateur_paie"

urlpatterns = [
    path('', views.create_bulletin, name='simu'),
    path('Accueil_simu', views.accueil, name='accueil'),
    path('telecharger_tableau/<int:bulletin_id>/', views.telecharger_tableau_pdf, name='telecharger_tableau'),
    path('historique', views.Historique,name='historique'),
    path('historique_net_to_brut', views.Historique_net_to_brut,name='historique_net_to_brut'),
    path('historique_cout_to_brut', views.Historique_cout_to_brut,name='historique_cout_to_brut'),
    path('bulletin/<int:bulletin_id>/', views.bulletin_detail, name='bulletin_detail'),
    path('edit_bulletin/<int:bulletin_id>/', views.edit_bulletin, name='edit_bulletin'),
    path('remove_bulletin/<int:bulletin_id>/', views.remove_bulletin, name='remove_bulletin'),
    path('bulletin2/<int:bulletin_id>/', views.bulletin2, name='bulletin2'),
    path('Net_to_Brut/', views.create_bulletin_Net_vers_Brut, name='Net_to_Brut'),
    path('Net_to_Brut_calcul/<int:bulletin_id>/', views.calculer_net_vers_brut, name='Net_to_Brut_calcul'),
    path('bulletin_net_to_brut/<int:bulletin_id>/', views.bulletin_detail_net_to_brut, name='bulletin_net_to_brut'), #le bulletin detail pour le net vers brut
    path('remove_bulletin_net_to_brut/<int:bulletin_id>/', views.remove_bulletin_net_to_brut, name='remove_bulletin_net_to_brut'),
    path('edit_bulletin_net_to_brut/<int:bulletin_id>/', views.edit_bulletin_net_to_brut, name='edit_bulletin_net_to_brut'),
    path('Cout_to_Brut/', views.create_bulletin_Cout_vers_Brut, name='Cout_to_Brut'),
    path('Cout_to_Brut_calcul/<int:bulletin_id>/', views.calculer_cout_vers_brut, name='Cout_to_Brut_calcul'),
    path('remove_bulletin_cout_to_brut/<int:bulletin_id>/', views.remove_bulletin_cout_to_brut, name='remove_bulletin_cout_to_brut'),
    path('bulletin_cout_to_brut/<int:bulletin_id>/', views.bulletin_detail_cout_to_brut, name='bulletin_cout_to_brut'), #le bulletin detail pour le cout vers brut
    path('edit_bulletin_cout_to_brut/<int:bulletin_id>/', views.edit_bulletin_cout_to_brut, name='edit_bulletin_cout_to_brut'),
    
]

ressources/models.py
from django.db import models
import json

class Condition(models.Model):
    nom = models.CharField(max_length=255)

    def __str__(self):
        return self.nom


class utilisateur(models.Model):
    nom = models.CharField(max_length=64, unique = False,verbose_name = "Nom")
    prenom = models.CharField(max_length=64, unique = False,verbose_name = "Prenom")
    email = models.CharField(max_length=64, unique = True,verbose_name = "Email")
    conditions_utili = models.CharField(max_length=200, unique = False)
    conditions_utili_m2m = models.ManyToManyField(Condition, blank=True)  # Nouveau champ

    def conditions_as_string(self):
        return ', '.join([condition.nom for condition in self.conditions_utili_m2m.all()])


    def set_conditions(self, lst):
        self.condtions_utili = json.dumps(lst)

    def get_conditions(self):
        return json.loads(self.condtions_utili)

    def __str__(self):
         return f"{self.prenom} {self.nom}"

    class Meta:
         verbose_name = "Utilisateur"
         verbose_name_plural = "Utilisateurs"



class objet(models.Model):
    nom = models.CharField(max_length=64, unique = True,verbose_name = "nom")
    famille1 = models.CharField(max_length=64, null=True, blank=True, unique = False, verbose_name = "Famille1")
    famille2 = models.CharField(max_length=64, null=True, blank=True, unique = False, verbose_name = "Famille2")
    famille3 = models.CharField(max_length=64, null=True, blank=True, unique = False, verbose_name = "Famille3")
    famille4 = models.CharField(max_length=64, null=True, blank=True, unique = False, verbose_name = "Famille3")
    conditions_objet = models.CharField(max_length=200, unique = False)
    conditions_objet_m2m = models.ManyToManyField(Condition, blank=True)  # Nouveau champ

    def conditions_as_string(self):
        return ', '.join([condition.nom for condition in self.conditions_objet_m2m.all()])


    def __str__(self):
         return self.nom
    
    def get_famille1_color(self):
        famille1_colors = {
            'Informatique': '#C8AD7F',
            'Véhicule': '#597535',
            # Ajoutez plus de familles et couleurs selon vos besoins
        }
        return famille1_colors.get(self.famille1, '#000000')  # Noir par défaut

    class Meta:
         verbose_name = "Objet"
         verbose_name_plural = "Objets"   


class resa(models.Model):
    obj = models.ForeignKey(objet, on_delete=models.CASCADE, verbose_name="Objet")
    user = models.ForeignKey(utilisateur, on_delete=models.CASCADE, verbose_name="Utilisateur")
    date_debut = models.DateTimeField()
    date_fin = models.DateTimeField()
    
    def __str__(self):
        return f"Réservation de {self.obj.nom} par {self.user}"

    class Meta:
        verbose_name = "Reservation"
        verbose_name_plural = "Reservations"

    def check_conflict(self):
        conflicts = resa.objects.filter(
            obj=self.obj,
            date_debut__lt=self.date_fin,
            date_fin__gt=self.date_debut
        )
        return conflicts
 


class nom_famille(models.Model):
    famille1 = models.CharField(max_length=64, default="Famille1", null=True, blank=True, unique = False, verbose_name = "Famille1")
    famille2 = models.CharField(max_length=64, default="Famille2", null=True, blank=True, unique = False, verbose_name = "Famille2")
    famille3 = models.CharField(max_length=64, default="Famille3", null=True, blank=True, unique = False, verbose_name = "Famille3")
    famille4 = models.CharField(max_length=64, default="Famille4", null=True, blank=True, unique = False, verbose_name = "Famille3")

    def __str__(self):
         return f"Famille1 : {self.famille1}, Famille2 : {self.famille2}, Famille2 : {self.famille2}, Famille2 : {self.famille2},"

    class Meta:
         verbose_name = "Objet"
         verbose_name_plural = "Objets"  

ressources/forms.py
from typing import Any
from django import forms
from .models import utilisateur, objet, resa, nom_famille, Condition

class ConditionForm(forms.ModelForm):
    class Meta:
        model = Condition
        fields = ['nom']

class utili_form(forms.ModelForm):
    conditions_utili_m2m = forms.ModelMultipleChoiceField(
        queryset=Condition.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
        label="Atouts"
    )

    class Meta:
        model = utilisateur
        fields = ["nom", "prenom", "email", "conditions_utili_m2m"]

class ObjetForm(forms.ModelForm):
    conditions_objet_m2m = forms.ModelMultipleChoiceField(
        queryset=Condition.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
        label="Conditions"
    )

    class Meta:
        model = objet
        fields = ['nom', 'famille1', 'famille2', 'famille3', 'famille4', 'conditions_objet_m2m']

def conditions_to_list(conditions_str):
    return [condition.strip() for condition in conditions_str.split(',')]


class ResaForm(forms.ModelForm):
    class Meta:
        model = resa
        fields = ['obj', 'user', 'date_debut', 'date_fin']
        widgets = {
            'obj': forms.HiddenInput(),
            'date_debut': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'date_fin': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }

    def __init__(self, *args, **kwargs):
        user_queryset = kwargs.pop('user_queryset', None)
        super().__init__(*args, **kwargs)
        if user_queryset is not None:
            self.fields['user'].queryset = user_queryset

    def clean(self):
        cleaned_data = super().clean()
        obj = cleaned_data.get('obj')
        date_debut = cleaned_data.get('date_debut')
        date_fin = cleaned_data.get('date_fin')

        if obj and date_debut and date_fin:
            new_resa = resa(obj=obj, date_debut=date_debut, date_fin=date_fin)
            conflicts = new_resa.check_conflict()
            if conflicts.exists():
                conflict_dates = "\n".join([f"{c.date_debut} to {c.date_fin}" for c in conflicts])
                raise forms.ValidationError(f"L'objet est déjà réservé pour les dates suivantes :\n{conflict_dates}")

        return cleaned_data


class Famille1Form(forms.ModelForm):
    class Meta:
        model = nom_famille
        fields = ['famille1']


class Famille2Form(forms.ModelForm):
    class Meta:
        model = nom_famille
        fields = ['famille1', 'famille2']

class Famille3Form(forms.ModelForm):
    class Meta:
        model = nom_famille
        fields = ['famille1', 'famille2', 'famille3']

class Famille4Form(forms.ModelForm):
    class Meta:
        model = nom_famille
        fields = ['famille1', 'famille2', 'famille3', 'famille4']

ressources/templates/ressources/objet-form.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Ajouter Objet</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'ressources/css/main.css' %}">
    <style>
        .custom-navbar {
            background-color: #073c47 !important;
            position: sticky;
            top: 0;
            z-index: 1030;
            height: 70px;
            padding-left: 0;
        }
        .custom-navbar .nav-item a:hover {
            color: #7dc4c4 !important;
            text-decoration: underline;
        }
        .wrapper {
            display: flex;
            height: 100vh;
            align-items: stretch;
        }
        .sidebar {
            min-width: 60px;
            max-width: 60px;
            background: #666666;
            color: #000000;
            transition: all 0.3s;
            padding-top: 20px;
            display: flex;
            flex-direction: column;
            align-items: center;
            position: relative;
        }
        .sidebar .nav-link {
            color: #000000 !important;
            padding: 10px 0;
            text-align: center;
        }
        .sidebar .navbar-nav {
            flex: 1;
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        .sidebar .nav-item {
            position: relative;
            margin-bottom: 20px;
        }
        .sidebar .nav-item a:hover {
            background-color: #073c47 !important;
            text-decoration: underline;
        }
        .sidebar .nav-item .dropdown-toggle::after {
            display: none;
        }
        .sidebar-header, .sidebar ul.components {
            border-bottom: none;
        }
        .dropdown-sidebar {
            display: none;
            position: absolute;
            left: 60px;
            top: 0;
            background: #073c47;
            min-width: 200px;
            padding-top: 20px;
            box-shadow: 2px 0 5px rgba(0,0,0,0.5);
            z-index: 1000;
        }
        .dropdown-sidebar .dropdown-item {
            color: #ffffff;
            padding: 10px 20px;
            text-decoration: none;
            display: block;
        }
        .dropdown-sidebar .dropdown-item:hover {
            background-color: #7dc4c4;
            color: #7dc4c4;
        }
        .sidebar-logo {
            margin-top: auto;
            padding: 10px;
        }
        .sidebar-logo img {
            width: 100%;
            height: auto;
        }
        .content {
            flex: 1;
            padding: 30px;
            overflow-y: auto;
            position: relative;
        }
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #7a7a7a51;
            margin: 0;
            display: flex;
            flex-direction: column;
            height: 100vh;
        }
    </style>
</head>
<body>
    <!-- Première barre de navigation supérieure -->
    <nav class="navbar navbar-expand-lg navbar-dark custom-navbar">
        <a class="navbar-brand" href="{% url 'accounts:accueil' %}">
            <img src="{% static 'ressources/css/logo.png' %}" alt="Hope Logo" style="height: 70px;">
        </a>
        <a class="navbar-brand" href="{% url 'ressources:index' %}">
            GESTIONNAIRE DE RESSOURCES | Accueil
        </a>
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="#">?</a></li>
                <li class="nav-item"><a class="nav-link" href="#"><img src="{% static 'ressources/css/profil.png' %}" style="width: 30px; height: 30px;"></a></li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Déconnexion</a>
                </li>
            {% endif %}
        </ul>
    </nav>

    <div class="wrapper">
        <!-- Barre latérale -->
        <nav id="sidebar" class="sidebar">
            <ul class="list-unstyled components navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ressources:index' %}">
                        <img src="{% static 'ressources/css/maison_blanche.png' %}" style="width: 25px; height: 25px;">
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ressources:calendar_view' %}">
                        <img src="{% static 'ressources/css/calendrier_blanc.png' %}" style="width: 25px; height: 25px;">
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" id="navbarDropdown1" role="button">
                        <img src="{% static 'ressources/css/liste_blanche.png' %}" style="width: 25px; height: 25px;">
                    </a>
                    <div class="dropdown-sidebar">
                        <a class="dropdown-item" href="{% url 'ressources:utili-liste' %}">Liste d'utilisateurs</a>
                        <a class="dropdown-item" href="{% url 'ressources:objet-liste' %}">Liste d'objets</a>
                        <a class="dropdown-item" href="{% url 'ressources:resa-liste' %}">Liste de réservations</a>
                        <a class="dropdown-item" href="{% url 'ressources:condi-liste' %}">Liste des conditions</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" id="navbarDropdown2" role="button">
                        <img src="{% static 'ressources/css/plus_blanc.png' %}" style="width: 25px; height: 25px;">
                    </a>
                    <div class="dropdown-sidebar">
                        <a class="dropdown-item" href="{% url 'ressources:create_user' %}">Ajout d'utilisateur</a>
                        <a class="dropdown-item" href="{% url 'ressources:create_objet' %}">Ajout d'objet</a>
                        <a class="dropdown-item" href="{% url 'ressources:ajout-resa' %}">Ajout de réservation</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" id="navbarDropdown3" role="button">
                        <img src="{% static 'ressources/css/settings_blanc.png' %}" style="width: 25px; height: 25px;">
                    </a>
                    <div class="dropdown-sidebar">
                        <a class="dropdown-item" href="{% url 'ressources:choix_famille' 1 %}">Parametres Familles</a>
                        <a class="dropdown-item" href="{% url 'ressources:create_condition' %}">Parametres Conditions/Atouts</a>
                    </div>
                </li>
            </ul>
        </nav>

        <!-- Contenu principal -->
        <div id="content" class="content">
            <div class="container mt-4">
                <h1>Ajouter Objet</h1>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_nom">Nom de l'objet</label>
                        {{ form.nom }}
                    </div>
                    <div class="form-group">
                        <label for="id_famille1">Famille 1</label>
                        {{ form.famille1 }}
                    </div>
                    <div class="form-group">
                        <label for="id_famille2">Famille 2</label>
                        {{ form.famille2 }}
                    </div>
                    <div class="form-group">
                        <label for="id_famille3">Famille 3</label>
                        {{ form.famille3 }}
                    </div>
                    <div class="form-group">
                        <label for="id_famille4">Famille 4</label>
                        {{ form.famille4 }}
                    </div>
                    <div class="form-group">
                        <h2>Conditions d'utilisation</h2>
                        {{ form.conditions_objet_m2m }}
                    </div>
                    <button type="submit" class="btn btn-primary">Valider</button>
                </form>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

ressources/templates/ressources/utili-form.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Ajouter Utilisateur</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'ressources/css/main.css' %}">
    <style>
        .custom-navbar {
            background-color: #073c47 !important;
            position: sticky;
            top: 0;
            z-index: 1030;
            height: 70px;
            padding-left: 0;
        }
        .custom-navbar .nav-item a:hover {
            color: #7dc4c4 !important;
            text-decoration: underline;
        }
        .wrapper {
            display: flex;
            height: 100vh;
            align-items: stretch;
        }
        .sidebar {
            min-width: 60px;
            max-width: 60px;
            background: linear-gradient(to top, #000000, #073c47);
            color: #000000;
            transition: all 0.3s;
            padding-top: 20px;
            display: flex;
            flex-direction: column;
            align-items: center;
            position: relative;
        }
        .sidebar .nav-link {
            color: #000000 !important;
            padding: 10px 0;
            text-align: center;
        }
        .sidebar .navbar-nav {
            flex: 1;
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        .sidebar .nav-item {
            position: relative;
            margin-bottom: 20px;
        }
        .sidebar .nav-item a:hover {
            background-color: #073c47 !important;
            text-decoration: underline;
        }
        .sidebar .nav-item .dropdown-toggle::after {
            display: none;
        }
        .sidebar-header, .sidebar ul.components {
            border-bottom: none;
        }
        .dropdown-sidebar {
            display: none;
            position: absolute;
            left: 60px;
            top: 0;
            background: #073c47;
            min-width: 200px;
            padding-top: 20px;
            box-shadow: 2px 0 5px rgba(0,0,0,0.5);
            z-index: 1000;
        }
        .dropdown-sidebar .dropdown-item {
            color: #ffffff;
            padding: 10px 20px;
            text-decoration: none;
            display: block;
        }
        .dropdown-sidebar .dropdown-item:hover {
            background-color: #7dc4c4;
            color: #7dc4c4;
        }
        .sidebar-logo {
            margin-top: auto;
            padding: 10px;
        }
        .sidebar-logo img {
            width: 100%;
            height: auto;
        }
        .content {
            flex: 1;
            padding: 30px;
            overflow-y: auto;
            position: relative;
        }
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #7a7a7a51;
            margin: 0;
            display: flex;
            flex-direction: column;
            height: 100vh;
        }
    </style>
</head>
<body>
    <!-- Première barre de navigation supérieure -->
    <nav class="navbar navbar-expand-lg navbar-dark custom-navbar">
        <a class="navbar-brand" href="{% url 'accounts:accueil' %}">
            <img src="{% static 'ressources/css/logo.png' %}" alt="Hope Logo" style="height: 70px;">
        </a>
        <a class="navbar-brand" href="{% url 'ressources:index' %}">
            GESTIONNAIRE DE RESSOURCES | Accueil
        </a>
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="#">?</a></li>
                <li class="nav-item"><a class="nav-link" href="#"><img src="{% static 'ressources/css/profil.png' %}" style="width: 30px; height: 30px;"></a></li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Déconnexion</a>
                </li>
            {% endif %}
        </ul>
    </nav>

    <div class="wrapper">
        <!-- Barre latérale -->
        <nav id="sidebar" class="sidebar">
            <ul class="list-unstyled components navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ressources:index' %}">
                        <img src="{% static 'ressources/css/maison_blanche.png' %}" style="width: 25px; height: 25px;">
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'ressources:calendar_view' %}">
                        <img src="{% static 'ressources/css/calendrier_blanc.png' %}" style="width: 25px; height: 25px;">
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" id="navbarDropdown1" role="button">
                        <img src="{% static 'ressources/css/liste_blanche.png' %}" style="width: 25px; height: 25px;">
                    </a>
                    <div class="dropdown-sidebar">
                        <a class="dropdown-item" href="{% url 'ressources:utili-liste' %}">Liste d'utilisateurs</a>
                        <a class="dropdown-item" href="{% url 'ressources:objet-liste' %}">Liste d'objets</a>
                        <a class="dropdown-item" href="{% url 'ressources:resa-liste' %}">Liste de réservations</a>
                        <a class="dropdown-item" href="{% url 'ressources:condi-liste' %}">Liste des conditions</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" id="navbarDropdown2" role="button">
                        <img src="{% static 'ressources/css/plus_blanc.png' %}" style="width: 25px; height: 25px;">
                    </a>
                    <div class="dropdown-sidebar">
                        <a class="dropdown-item" href="{% url 'ressources:create_user' %}">Ajout d'utilisateur</a>
                        <a class="dropdown-item" href="{% url 'ressources:create_objet' %}">Ajout d'objet</a>
                        <a class="dropdown-item" href="{% url 'ressources:ajout-resa' %}">Ajout de réservation</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" id="navbarDropdown3" role="button">
                        <img src="{% static 'ressources/css/settings_blanc.png' %}" style="width: 25px; height: 25px;">
                    </a>
                    <div class="dropdown-sidebar">
                        <a class="dropdown-item" href="{% url 'ressources:choix_famille' 1 %}">Parametres Familles</a>
                        <a class="dropdown-item" href="{% url 'ressources:create_condition' %}">Parametres Conditions/Atouts</a>
                    </div>
                </li>
            </ul>
        </nav>

        <!-- Contenu principal -->
        <div id="content" class="content">
            <div class="container mt-4">
                <h1>Ajouter Utilisateur</h1>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_nom">Nom</label>
                        {{ form.nom }}
                    </div>
                    <div class="form-group">
                        <label for="id_prenom">Prenom</label>
                        {{ form.prenom }}
                    </div>
                    <div class="form-group">
                        <label for="id_email">Email</label>
                        {{ form.email }}
                    </div>
                    <div class="form-group">
                        <h2>Atouts</h2>
                        {{ form.conditions_utili_m2m }}
                    </div>
                    <button type="submit" class="btn btn-primary">Valider</button>
                </form>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>