Chatbot/urls.py
from django.urls import path
from . import views

app_name = "Chatbot"

urlpatterns = [
    path('accueil_chatbot', views.accueil_chatbot, name='accueil_chatbot'),
    path('chatbot_app', views.chatbot_application, name='chatbot_app'),
    path('documents_chatbot', views.documents_chatbot, name='documents_chatbot'),
    path('ajout_doc_temp', views.ajout_document_template, name='ajout_doc_temp'),
    path('ajout_doc_fct', views.ajout_document_fonction, name='ajout_doc_fct'),
    path('remove_doc/<str:document_name>', views.remove_doc, name='remove_doc'), 
    path('get_sources', views.get_sources, name='get_sources'),
    path('documents_chatbot2', views.documents_chatbot2, name='documents_chatbot2'),
    

]

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('', views.accueil_user, name='accueil'),
    path('contact/', views.contact, name='contact'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('signup/entreprise/', views.entreprise_signup, name='entreprise_signup'),
    path('add_salarie/', views.add_salarie, name='add_salarie'),
    path('salarie_list/', views.salarie_list, name='salarie_list'),
    path('delete_salarie/<int:salarie_id>/', views.delete_salarie, name='delete_salarie'),
]

gestion_ressources_V2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ress/', include('ressources.urls')),
    path('accounts/', include('accounts.urls')),
    path('simulateur_paie/', include('simulateur_paie.urls')),
    path('Chatbot/', include('Chatbot.urls')),
]

ressources/urls.py
from django.urls import path
from . import views

app_name = "ressources"

urlpatterns = [
    path('', views.index, name='index'),
    path('accueil', views.accueil, name='accueil'),
    path('ajouter-utilisateur/', views.create_user, name='create_user'),
    path('ajouter-objet/', views.create_objet, name='create_objet'),
    path('ajouter-resa/<int:obj_id>/', views.create_resa, name='create_resa'),
    path('edit-utilisateur/<int:utili_id>/', views.edit_user, name='edit_user'),
    path('edit-objet/<int:obj_id>/', views.edit_objet, name='edit_objet'),
    path('edit-resa/<int:resa_id>/', views.edit_resa, name='edit_resa'),
    path('edit-condi/<int:resa_id>/', views.edit_condi, name='edit_condi'),
    path('supp-utilisateur/<int:utili_id>/', views.remove_user, name='remove_user'),
    path('supp-objet/<int:obj_id>/', views.remove_objet, name='remove_objet'),
    path('supp-resa/<int:resa_id>/', views.remove_resa, name='remove_resa'),
    path('supp-condi/<int:condi_id>/', views.remove_condi, name='remove_condi'),
    path('events/', views.calendar_events, name='calendar_events'),
    path('calendar/', views.calendar_view, name='calendar_view'),
    path('choix-famille/<int:nbr_fam>/', views.choix_famille, name='choix_famille'),
    path('utili-liste', views.liste_utili, name='utili-liste'),
    path('objet-liste', views.liste_objet, name='objet-liste'),
    path('resa-liste', views.liste_resa, name='resa-liste'),
    path('ajout-resa', views.create_resa2, name='ajout-resa'),
    path('ajouter-condition/', views.create_condition, name='create_condition'),
    path('condi-liste/', views.liste_condition, name='condi-liste')
]

simulateur_paie/urls.py
from django.urls import path
from . import views

app_name = "simulateur_paie"

urlpatterns = [
    path('', views.create_bulletin, name='simu'),
    path('Accueil_simu', views.accueil, name='accueil'),
    path('telecharger_tableau/<int:bulletin_id>/', views.telecharger_tableau_pdf, name='telecharger_tableau'),
    path('historique', views.Historique,name='historique'),
    path('historique_net_to_brut', views.Historique_net_to_brut,name='historique_net_to_brut'),
    path('historique_cout_to_brut', views.Historique_cout_to_brut,name='historique_cout_to_brut'),
    path('bulletin/<int:bulletin_id>/', views.bulletin_detail, name='bulletin_detail'),
    path('edit_bulletin/<int:bulletin_id>/', views.edit_bulletin, name='edit_bulletin'),
    path('remove_bulletin/<int:bulletin_id>/', views.remove_bulletin, name='remove_bulletin'),
    path('bulletin2/<int:bulletin_id>/', views.bulletin2, name='bulletin2'),
    path('Net_to_Brut/', views.create_bulletin_Net_vers_Brut, name='Net_to_Brut'),
    path('Net_to_Brut_calcul/<int:bulletin_id>/', views.calculer_net_vers_brut, name='Net_to_Brut_calcul'),
    path('bulletin_net_to_brut/<int:bulletin_id>/', views.bulletin_detail_net_to_brut, name='bulletin_net_to_brut'), #le bulletin detail pour le net vers brut
    path('remove_bulletin_net_to_brut/<int:bulletin_id>/', views.remove_bulletin_net_to_brut, name='remove_bulletin_net_to_brut'),
    path('edit_bulletin_net_to_brut/<int:bulletin_id>/', views.edit_bulletin_net_to_brut, name='edit_bulletin_net_to_brut'),
    path('Cout_to_Brut/', views.create_bulletin_Cout_vers_Brut, name='Cout_to_Brut'),
    path('Cout_to_Brut_calcul/<int:bulletin_id>/', views.calculer_cout_vers_brut, name='Cout_to_Brut_calcul'),
    path('remove_bulletin_cout_to_brut/<int:bulletin_id>/', views.remove_bulletin_cout_to_brut, name='remove_bulletin_cout_to_brut'),
    path('bulletin_cout_to_brut/<int:bulletin_id>/', views.bulletin_detail_cout_to_brut, name='bulletin_cout_to_brut'), #le bulletin detail pour le cout vers brut
    path('edit_bulletin_cout_to_brut/<int:bulletin_id>/', views.edit_bulletin_cout_to_brut, name='edit_bulletin_cout_to_brut'),
    
]

accounts/models.py
# accounts/models.py
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models
from django.conf import settings

class CustomUserManager(UserManager):
    pass

class CustomUser(AbstractUser):
    is_entreprise = models.BooleanField(default=False)
    is_salarie = models.BooleanField(default=False)

class Entreprise(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    nom_entreprise = models.CharField(max_length=255)
    est_client = models.BooleanField(default=False)  # A valider manuellement dans l'admin
    validated = models.BooleanField(default=False)  # Indicates if admin has validated


    def __str__(self):
        return self.nom_entreprise

class Salarie(models.Model):
    entreprise = models.ForeignKey(Entreprise, on_delete=models.CASCADE, related_name='salaries')
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    prenom = models.CharField(max_length=100)
    nom = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.prenom} {self.nom}"

ressources/models.py
from django.db import models
import json

class Condition(models.Model):
    nom = models.CharField(max_length=255)

    def __str__(self):
        return self.nom


class utilisateur(models.Model):
    nom = models.CharField(max_length=64, unique = False,verbose_name = "Nom")
    prenom = models.CharField(max_length=64, unique = False,verbose_name = "Prenom")
    email = models.CharField(max_length=64, unique = True,verbose_name = "Email")
    conditions_utili = models.CharField(max_length=200, unique = False)
    conditions_utili_m2m = models.ManyToManyField(Condition, blank=True)  # Nouveau champ

    def conditions_as_string(self):
        return ', '.join([condition.nom for condition in self.conditions_utili_m2m.all()])


    def set_conditions(self, lst):
        self.condtions_utili = json.dumps(lst)

    def get_conditions(self):
        return json.loads(self.condtions_utili)

    def __str__(self):
         return f"{self.prenom} {self.nom}"

    class Meta:
         verbose_name = "Utilisateur"
         verbose_name_plural = "Utilisateurs"



class objet(models.Model):
    nom = models.CharField(max_length=64, unique = True,verbose_name = "nom")
    famille1 = models.CharField(max_length=64, null=True, blank=True, unique = False, verbose_name = "Famille1")
    famille2 = models.CharField(max_length=64, null=True, blank=True, unique = False, verbose_name = "Famille2")
    famille3 = models.CharField(max_length=64, null=True, blank=True, unique = False, verbose_name = "Famille3")
    famille4 = models.CharField(max_length=64, null=True, blank=True, unique = False, verbose_name = "Famille3")
    conditions_objet = models.CharField(max_length=200, unique = False)
    conditions_objet_m2m = models.ManyToManyField(Condition, blank=True)  # Nouveau champ

    def conditions_as_string(self):
        return ', '.join([condition.nom for condition in self.conditions_objet_m2m.all()])


    def __str__(self):
         return self.nom
    
    def get_famille1_color(self):
        famille1_colors = {
            'Informatique': '#C8AD7F',
            'Véhicule': '#597535',
            # Ajoutez plus de familles et couleurs selon vos besoins
        }
        return famille1_colors.get(self.famille1, '#000000')  # Noir par défaut

    class Meta:
         verbose_name = "Objet"
         verbose_name_plural = "Objets"   


class resa(models.Model):
    obj = models.ForeignKey(objet, on_delete=models.CASCADE, verbose_name="Objet")
    user = models.ForeignKey(utilisateur, on_delete=models.CASCADE, verbose_name="Utilisateur")
    date_debut = models.DateTimeField()
    date_fin = models.DateTimeField()
    
    def __str__(self):
        return f"Réservation de {self.obj.nom} par {self.user}"

    class Meta:
        verbose_name = "Reservation"
        verbose_name_plural = "Reservations"

    def check_conflict(self):
        conflicts = resa.objects.filter(
            obj=self.obj,
            date_debut__lt=self.date_fin,
            date_fin__gt=self.date_debut
        )
        return conflicts
 


class nom_famille(models.Model):
    famille1 = models.CharField(max_length=64, default="Famille1", null=True, blank=True, unique = False, verbose_name = "Famille1")
    famille2 = models.CharField(max_length=64, default="Famille2", null=True, blank=True, unique = False, verbose_name = "Famille2")
    famille3 = models.CharField(max_length=64, default="Famille3", null=True, blank=True, unique = False, verbose_name = "Famille3")
    famille4 = models.CharField(max_length=64, default="Famille4", null=True, blank=True, unique = False, verbose_name = "Famille3")

    def __str__(self):
         return f"Famille1 : {self.famille1}, Famille2 : {self.famille2}, Famille2 : {self.famille2}, Famille2 : {self.famille2},"

    class Meta:
         verbose_name = "Objet"
         verbose_name_plural = "Objets"  

accounts/forms.py
# accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser, Entreprise, Salarie

# forms.py
class EntrepriseSignUpForm(UserCreationForm):
    nom_entreprise = forms.CharField(max_length=255)
    est_client = forms.BooleanField(required=False)

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_entreprise = True
        if commit:
            user.save()
            Entreprise.objects.create(
                user=user,
                nom_entreprise=self.cleaned_data['nom_entreprise'],
                est_client=self.cleaned_data['est_client'],
                validated=False if self.cleaned_data['est_client'] else True
            )
        return user

class SalarieSignUpForm(UserCreationForm):
    prenom = forms.CharField(max_length=100)
    nom = forms.CharField(max_length=100)

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        self.entreprise = kwargs.pop('entreprise', None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_salarie = True
        if commit:
            user.save()
            Salarie.objects.create(user=user, entreprise=self.entreprise,
                                   prenom=self.cleaned_data['prenom'],
                                   nom=self.cleaned_data['nom'])
        return user

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test

import os
import pandas as pd
from django.conf import settings

from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Salarie



def accueil_user(request):
    return render(request,"accounts/accueil.html",{})


def contact(request):
    return render(request,"accounts/contact.html",{})


def login_user(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]

        user = authenticate(request, username = username, password = password)

        if user is not None :
            login(request, user)
            return redirect("accounts:accueil")
        else:
            messages.info(request, "Identifiant ou mot de passe incorrect")
    
    form = AuthenticationForm()
    return render(request, "accounts/login.html", { "form" : form})



def logout_user(request):
    logout(request)
    return redirect("accounts:accueil")


def register_user(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("ressources:index")
    else:
        form = UserCreationForm()

    return render(request, "accounts/register.html", {"form":form})



# accounts/views.py
from django.contrib.auth.decorators import login_required
from .forms import EntrepriseSignUpForm, SalarieSignUpForm
from .models import Entreprise, Salarie

def entreprise_signup(request):
    if request.method == 'POST':
        form = EntrepriseSignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('accounts:accueil')
    else:
        form = EntrepriseSignUpForm()
    return render(request, 'accounts/register.html', {'form': form})

@login_required
def add_salarie(request):
    entreprise = Entreprise.objects.get(user=request.user)
    if request.method == 'POST':
        form = SalarieSignUpForm(request.POST, entreprise=entreprise)
        if form.is_valid():
            form.save()
            return redirect('accounts:salarie_list')
    else:
        form = SalarieSignUpForm()
    return render(request, 'accounts/register_employee.html', {'form': form})

@login_required
def salarie_list(request):
    entreprise = Entreprise.objects.get(user=request.user)
    salaries = entreprise.salaries.all()

    if request.method == 'POST':
        form = SalarieSignUpForm(request.POST, entreprise=entreprise)
        if form.is_valid():
            form.save()
            return redirect('accounts:salarie_list')
    else:
        form = SalarieSignUpForm()
    return render(request, 'accounts/salarie_list.html', {'form': form,'salaries': salaries})



from django.contrib import messages


@login_required
def delete_salarie(request, salarie_id):
    try:
        book = Salarie.objects.get(pk = salarie_id)
        book.delete()
    except Salarie.DoesNotExist:
        return redirect("accounts:salarie_list")
    return redirect("accounts:salarie_list")

accounts/templates/accounts/accueil.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>🍀 HOPE - Accueil</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>

        .header-content {
            text-align: left;
            padding: 100px 20px; /* Increased padding for more vertical space */
            color: #073c47;
            position: relative;
            z-index: 1;
            padding-left: 100px; /* added padding to the left */
            min-height: 600px; /* Increased minimum height */
        }

        .header-content::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            z-index: -1;
        }

        .header-content h1 {
            font-size: 3rem;
            font-weight: bold;
            margin-bottom: 1rem;
        }

        .header-content h2 {
            font-size: 1.5rem;
            margin-bottom: 2rem;
            color: #073c47; /* Light Teal */
        }

        .header-content .btn-primary {
            background-color: #1a646d; /* Medium Teal */
            border-color: #1a646d;
        }

        .header-content .btn-primary:hover {
            background-color: #073c47; /* Medium Green */
            border-color: #ffffff;
        }

        .content {
            text-align: center;
            padding: 50px 20px;
        }

        .content .icon {
            display: inline-block;
            margin: 20px;
        }

        .content .icon img {
            width: 100px;
            height: 100px;
            background-color: #073c47; /* Dark Teal background for icons */
            border-radius: 50%;
            padding: 20px;
        }

        .content .icon p {
            font-size: 1.1rem;
            font-weight: bold;
            color: #073c47; /* Dark Teal */
            margin-top: 10px;
        }



        body {
            font-family:'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
            background-image: url("{% static 'ressources/css/fond_ecran.png' %}");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            color: #073c47; /* Dark Teal */
        }

        

        /* First Navbar (White Background) */
        .first-navbar {
            background-color: white;
            border-bottom: 2px solid #dcdcdc;
            padding: 0px 0;
            padding-right: 100px;
        }
        .first-navbar .navbar-brand img {
            height: 100px; /* Increased logo size */
            margin-left: 80px; /* Left margin to align with other elements */
            margin-top: 15px;
        }
        .first-navbar .nav-item {
            margin-right: 20px;
        }
        .first-navbar .nav-item a {
            color: #073c47;
            font-weight: bold;
            text-decoration: none;
        }
        .first-navbar .nav-item a:hover {
            text-decoration: underline;
        }

        /* Second Navbar (White Background, Dark Teal Text) */
        .second-navbar {
            background-color: white;
            border-bottom: 2px solid #dcdcdc;
            padding: 10px 0;
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.4);
        }
        .second-navbar .navbar-nav {
            margin-left: 80px; /* Align all items to the left, starting with the margin */
        }
        .second-navbar .nav-item {
            margin-right: 20px;
        }
        .second-navbar .nav-item a {
            color: #073c47;
            font-weight: bold;
            text-decoration: none;
            transition: color 0.3s ease, border-bottom 0.3s ease; /* Ajoutez une transition pour la couleur et la bordure */
        }

        .second-navbar .nav-item a:hover {
            color: #7dc4c4; /* Changez la couleur au survol */
            border-bottom: 2px solid #7dc4c4; /* Ajoutez une bordure inférieure au survol */
        }
        .second-navbar .nav-item.active a {
            color: #7dc4c4; /* Couleur de soulignement */
            border-bottom: 2px solid #7dc4c4;
        }
        

        footer {
            background-color: #073c47; /* Dark Teal */
            color: #ffffff;
            padding: 30px 20px;
            text-align: left;
            font-family: 'Arial', sans-serif; /* Match the font */
        }

        footer h3 {
            color: #7dc4c4; /* Light Green */
            font-weight: bold;
            font-size: 1.2rem;
            margin-bottom: 1rem;
        }

        footer .footer-column {
            margin-bottom: 20px;
        }

        footer .footer-column ul {
            list-style: none;
            padding: 0;
        }

        footer .footer-column ul li {
            margin-bottom: 10px;
        }

        footer .footer-column ul li a {
            color: #ffffff;
            text-decoration: none;
        }

        footer .footer-column ul li a:hover {
            color: #7dc4c4; /* Light Teal */
            text-decoration: underline;
        }

        footer .contact-info {
            line-height: 1.5; /* Adjust line height for spacing */
        }

        .paragraph-container {
            position: relative;
            height: 50px; /* Ajuste la hauteur en fonction de la taille de ton paragraphe */
        }

        .paragraph {
            position: absolute;
            opacity: 0;
            transition: opacity 1s ease-in-out;  /* Transition smooth sur l'opacité */
            width: 100%;
        }

        .paragraph.active {
            opacity: 1;  /* L'élément actif devient visible */
        }

        /* Particle effect */
        #particles-js {
            position: fixed;
            width: 100%;
            height: 100%;
            z-index: -2;
            background-color: transparent;
        }


    </style>
</head>
<body>
    <!-- First Navbar -->
    <nav class="navbar navbar-expand-lg first-navbar">
        <a class="navbar-brand" href="{% url 'accounts:accueil' %}">
            <img src="{% static 'ressources/css/logo2.png' %}" alt="Hope Logo">
        </a>
        <div class="collapse navbar-collapse" id="navbarFirstNav">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    {% if user.is_superuser %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}"><img src="{% static 'ressources/css/admin.png' %}" style="width: 20px; height: 20px;margin-right: 5px;margin-bottom: 5px;">
                            Page d'administration</a></li>
                    {% endif %}
                    {% if user.is_entreprise %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:salarie_list' %}"><img src="{% static 'ressources/css/collaborateur.png' %}" style="width: 20px; height: 20px;margin-right: 5px;margin-bottom: 5px;">
                            Gestion des collaborateurs</a></li>
                    {% endif %}
                    <li class="nav-item"><a class="nav-link" href="#"><img src="{% static 'ressources/css/profil4.png' %}" style="width: 20px; height: 20px;margin-right: 5px;margin-bottom: 5px;">
                        {{ user.username }}</a></li>
                    <li class="nav-item"><a class="nav-link">|</a></li>
                    <li class="nav-item"><a class="nav-link" href="#">Aide</a></li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}">
                            <img src="{% static 'ressources/css/deconnexion.png' %}" style="width: 20px; height: 20px;">
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Connexion</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:register' %}">Inscription</a></li>
                    <li class="nav-item"><a class="nav-link">|</a></li>
                    <li class="nav-item"><a class="nav-link" href="#">Aide</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>


    <!-- Second Navbar -->
    <nav class="navbar navbar-expand-lg second-navbar">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSecondNav" aria-controls="navbarSecondNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSecondNav">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" href="{% url 'ressources:accueil' %}">Gestionnaire de ressources</a></li>
                <li class="nav-item {% if request.path == '/simulateur_paie/' %}active{% endif %}">
                    <a class="nav-link" href="{% url 'simulateur_paie:accueil' %}">Simulateur de paie</a>
                </li>    
                <li class="nav-item"><a class="nav-link" href="{% url 'Chatbot:accueil_chatbot' %}">Chatbot</a></li>
                <li class="nav-item"><a class="nav-link" href="#">Nos services</a></li>
                <li class="nav-item"><a class="nav-link" href="#">A propos de nous</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:contact' %}">Contact</a></li>
            </ul>
        </div>
    </nav>


    <div class="header-content">
        <div class="paragraph-container">
            <p class="paragraph active">Gestionnaire de ressources</p>
            <p class="paragraph">Simulateur de paie</p>
            <p class="paragraph">Chatbot</p>
        </div>
        <h1><em>SERVICES & LOGICIELS DANS</em></h1>
        <h1><i>LA GESTION SOCIALE DE</i></h1>
        <h1><i>VOTRE ENTREPRISE</i></h1>
        <h2><em>BASE A MONACO</em></h2>

    </div>


    

    

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-6 footer-column">
                    <h3>Coordonnées</h3>
                    <div class="contact-info">
                        <p>HOPE SARL</p>
                        <p>Gildo Pastor Center,</p>
                        <p>7 Rue du Gabian</p>
                        <p>98000 Monaco</p>
                        <p>Tél: +33 6 03 62 25 80</p>
                        <p>Email: guillemotkentin@gmail.com</p>
                    </div>
                </div>
                <div class="col-md-6 footer-column">
                    <h3>Liens</h3>
                    <ul>
                        <li><a href="#">Infos Pratiques</a></li>
                        <li><a href="#">Actualités</a></li>
                        <li><a href="#">Mentions légales</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>


    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
        const paragraphs = document.querySelectorAll(".paragraph");
        let currentIndex = 0;

        setInterval(() => {
            // Retire la classe active du paragraphe actuel
            paragraphs[currentIndex].classList.remove("active");

            // Passe au paragraphe suivant, ou revient au premier si c'est le dernier
            currentIndex = (currentIndex + 1) % paragraphs.length;

            // Ajoute la classe active au nouveau paragraphe
            paragraphs[currentIndex].classList.add("active");
        }, 3500);  // Changer de paragraphe toutes les 5 secondes
        });


        
    </script>
</body>
</html>